use ETA_MAKR2014_2019
GO

SELECT STKKOD, STKCINSI, SUBSTRING(STKCINSI, CHARINDEX('', STKCINSI), CHARINDEX('"', STKCINSI)) + (SELECT CASE WHEN STKCINSI LIKE '%"%' THEN '"' END)  AS BOYUT
FROM dbo.STKKART
WHERE STKKOD LIKE '70%' AND NOT STKKOD LIKE '709%'